version: '3.9'

services:
    python:
        container_name: 'cloud-python'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - .env
        volumes:
            - .:/app
